### ISSUE TITLE
need a friendly way to remind user to install mksquashfs

### ISSUE THREAD

**Issue by pmq20** [pmq20/node-compiler#20]
```
C:\nodejs\Application>nodec bin\www.js -r C:\nodejs\Application -d c:\nodejs\tmp
Node.js Compiler (nodec) v0.9.3 (runtime 7.5.0)

Entrance: C:/nodejs/Application/bin/www.js
Options: {:root=>"C:\\nodejs\\Application", :tmpdir=>"c:/nodejs/tmp", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"nosign", :output=>"C:/nodejs/Application/a.exe"}

-> mkdir -p c:/nodejs/tmp
-> cp -r "C:/__enclose_io_memfs__/_local_/node" "c:/nodejs/tmp/node"
-> rm -rf c:/nodejs/tmp/__work_dir__
-> mkdir -p c:/nodejs/tmp/__work_dir__
-> cp -r "C:/nodejs/Application" "c:/nodejs/tmp/__work_dir__/__enclose_io_memfs__"
-> cd c:/nodejs/tmp/__work_dir__/__enclose_io_memfs__
-> Running ["\"npm\" -v"]
2.14.4
-> Running ["\"npm\" install"]
-> cd C:/nodejs/Application
-> cd c:/nodejs/tmp/__work_dir__/__enclose_io_memfs__
-> cd C:/nodejs/Application
-> cd c:/nodejs/tmp/node
-> rm -f deps/libsquash/sample/enclose_io_memfs.squashfs
-> rm -f deps/libsquash/sample/enclose_io_memfs.c
-> Running ["mksquashfs -version"]
C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:26:in `spawn': No such file or directory - mksquashfs -version (Errno::ENOENT)
        from C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:26:in `run'
        from C:/__enclose_io_memfs__/_local_/lib/compiler.rb:155:in `block in make_enclose_io_memfs'
        from C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `block in chdir'
        from C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `chdir'
        from C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `chdir'
        from C:/__enclose_io_memfs__/_local_/lib/compiler.rb:152:in `make_enclose_io_memfs'
        from C:/__enclose_io_memfs__/_local_/lib/compiler.rb:113:in `run!'
        from /__enclose_io_memfs__/_local_/bin/nodec:115:in `<main>'
```

可以先用着这个 https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip

我再想想怎么提示用户装这个

**Comment by pmq20** [comment]
added prerequisites to install instructions
