### ISSUE TITLE
No such file or directory @compiler.rb

### ISSUE THREAD

**Issue by MM2404** [pmq20/node-compiler#47]
after running nodec .\app\app.js --output=output/app I was encountering the following error:

-> cd D:/inetpub/wwwbasis/MyMemo
-> cd C:/Users/Admin/AppData/Local/Temp/nodec/__work_dir__/__enclose_io_memfs__
D:/__enclose_io_memfs__/_local_/lib/compiler.rb:173:in ``': No such file or directory - git status (Errno::ENOENT)
        from D:/__enclose_io_memfs__/_local_/lib/compiler.rb:173:in `block in npm_install'
        from D:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `block in chdir'
        from D:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `chdir'
        from D:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:33:in `chdir'
        from D:/__enclose_io_memfs__/_local_/lib/compiler.rb:171:in `npm_install'
        from D:/__enclose_io_memfs__/_local_/lib/compiler.rb:141:in `run!'
        from /__enclose_io_memfs__/_local_/bin/nodec:143:in `<main>'
PS D:\inetpub\wwwbasis\MyMemo>

Used nodec version: 1.0.0

can you tell me what that means or how to fix it?

**Comment by MM2404** [comment]
Because of a mistake which was my fault, I was able to run nodec on my project. I am using the Node Version Manager and Node v4.4.7 was activated and I started nodec which failed with the error message from my first post. After that  I switched the Node Version to the suggested v8.1.1 without "--clean-tmpdir" and the compilation was going on.  The output was useless and now I have to find out why...

**Comment by pmq20** [comment]
The error looks like that git is not installed.
