### ISSUE TITLE
Example not run,/__enclose_io_memfs__/node_modules/.bin/egg-bin

### ISSUE THREAD

**Issue by Fov6363** [pmq20/node-compiler#50]
一.by example,but not can run.

```
➜  tmp ./a.out dev
module.js:487
    throw err;
    ^

Error: Cannot find module '/__enclose_io_memfs__/node_modules/.bin/egg-bin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:162:16)
    at bootstrap_node.js:579:3
```
二.ENV:
```
➜  tmp uname -a
Darwin YUANYUANdeMacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
➜  tmp node -v
v8.1.1
➜  tmp npm -v
5.0.3
➜  tmp gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
➜  tmp /usr/bin/make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
thanks

**Comment by pmq20** [comment]
Another similar issue: https://github.com/pmq20/node-compiler/issues/59

**Comment by pmq20** [comment]
@Fov6363 It turns out that the entrance is not a valid JavaScript file. `node_modules/.bin/egg-bin` and `node_modules/.bin/egg-bin.cmd` are actually shell scripts and batch programs (or symbolic links in some cases) that all point to `node_modules/egg-bin/bin/egg-bin.js`.

Running it with the real entrance fixes the problem, i.e. `nodec node_modules/egg-bin/bin/egg-bin.js`.

**Comment by pmq20** [comment]
It's working as per 845b547f71e0c83d6becc21bdbbdae39c152ce23

![image](https://user-images.githubusercontent.com/13315/28605738-dfafb190-7205-11e7-8642-67895e169160.png)

**Comment by Fov6363** [comment]
thanks;
I will try again;
