### ISSUE TITLE
Does node-compiler work on ARM server?

### ISSUE THREAD

**Issue by geekycompy** [pmq20/node-compiler#66]
Hi,
I am trying out an ARM server. Would node-compiler work in it?

Thanks.

**Comment by pmq20** [comment]
I have not tried it. Pull requests are welcome.

geekycompy <notifications@github.com>于2017年7月20日 周四23:17写道：

**Comment by geekycompy** [comment]
Can I try to compile this there?

**Comment by pmq20** [comment]
@geekycompy Sure. Same instructions as other UNIX platform, assuming that you are using a UNIX operating system. You could also consult the build guide from Node.js, which serves the same purpose. https://github.com/nodejs/node/blob/master/BUILDING.md

**Comment by Ni-vek** [comment]
Yes it does! At least on a raspberry pi 3, with an UNIX armv7 or aarch64. You just have to clone node-compiler on your server and run `./node-compiler/bin/nodec` with the same parameters as you would do with releases

**Comment by arthurmoises** [comment]
Hi Ni-vek! 

First, thank you all for excellent tool and great explanations!

Do I need to have ruby in order to run nodec, Ni-vek? I just installed it, but I'm getting the following error:
 
```
[Build]    Step 14/16 : RUN ./node-packer/bin/nodec --skip-npm-install -r . index.js
[Build]     ---> Running in 1be06d3cc17f
[Build]    /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/src/app/node-packer/lib/compiler.rb:149: syntax error, unexpected '.' (SyntaxError)
[Build]        @package_json = @npm_package&.package_json
[Build]                                      ^
[Build]    	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[Build]    	from ./node-packer/bin/nodec:12:in `<main>'
[Build]    Removing intermediate container 1be06d3cc17f
[Error]    Build failed: The command '/bin/sh -c ./node-packer/bin/nodec --skip-npm-install -r . index.js' returned a non-zero code: 1
[Info]     Uploading successful layers to registry for caching purposes

```

I'm building a project in resin.io. The relevant parts of my Dockerfile.template are:

```
RUN apt-get update \
	&& apt-get install -y \
#...
    squashfs-tools \
		ruby \
#...
RUN git clone https://github.com/pmq20/node-packer.git
RUN ./node-packer/bin/nodec --skip-npm-install -r . index.js
```

Thanks a lot in advance!

**Comment by pmq20** [comment]
This is due to Ruby version being too low for the "&." operator.
