### ISSUE TITLE
error with module canvas1.6

### ISSUE THREAD

**Issue by dackmatt** [pmq20/node-compiler#68]
compile successfully but can't run it take's
Error: The specified module could not be found.
\\?\C:\__enclose_io_memfs__\node_modules\canvas\build\Release\canvas.node 
    at Object.Module._extensions..node (module.js:598:18)
but module snappy and node-sass are working perfect . pls help.
best wishes

**Comment by pmq20** [comment]
Thanks for reporting. Let me try reproducing this locally. Any code that could help reproduce is appreciated.

**Comment by huangapple** [comment]
This BUG still exists。

---------------------------------------------------------------------------------------------------
module.js:602
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\__enclose_io_memfs__\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\__enclose_io_memfs__\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
--------------------------------------------------------------------------------------------
